//jshint esversion:6

const express=require("express");
const https=require("https");
const bodyParser=require("body-parser");
const request = require("request");
const { query } = require("express");
require('dotenv').config(); //for security of API key
// const { url } = require("inspector");
// const { request } = require("http");

const app=express();

app.set("view engine", "ejs"); // this tells the app generated by express to use ejs as its view engine - refer to the docs

// for encoding the data
app.use(bodyParser.urlencoded({extended:true})); // when the data is rendered from html file then the body parser requires this piece of code
app.use(express.static(__dirname + '/public')); // used for css files

app.get("/", function(req,res){
    res.sendFile(__dirname+"/index.html"); 
});

const apiKey= process.env.OPEN_WEATHER_API_KEY

app.post("/",function(req,res){
        request("https://api.openweathermap.org/data/2.5/weather?id=2172797&appid="+ apiKey +"", function(error, response, body){
            
            // to receive the api response in the JSON Format
            var dataAPI=JSON.parse(response.body);
            console.log(dataAPI);

        });
        const queryInput= req.body.cityName;
        const units= "metric";
        const url= "https://api.openweathermap.org/data/2.5/weather?q="+ queryInput +"&appid="+ apiKey +"&units="+ units +"";
        https.get(url, function(response){
            console.log(response.statusCode); // to get the status code in the terminal
            // while using the api call response data
            response.on("data", function(data){
                const weatherData= JSON.parse(data);
                const temp= weatherData.main.temp;
                const weatherDescription= weatherData.weather[0].description;
                const icon= weatherData.weather[0].icon;
                const imageUrl="http://openweathermap.org/img/wn/" + icon + "@2x.png";

                const query = queryInput.charAt(0).toUpperCase() + queryInput.slice(1); // capitalising the first letter of the entered query

                // res.write("<p>The weather is currently "+ weatherDescription +"</p>");
                // res.write("<h1>The temperature in "+ query +" is "+ temp +" degree celsius</h1>");
                // res.write("<img src="+ imageUrl +" >");
                res.render('output',{city: query, temperature: temp, description: weatherDescription, image: imageUrl});

                res.end();
            });

        });
});

app.listen(5000 || process.env.PORT ,function(req,res){
    console.log("server is running at port 5000");
});

