//jshint esversion:6

const express=require("express");
const https=require("https");
const bodyParser=require("body-parser");
const request = require("request");
const { query } = require("express");
require('dotenv').config(); //for security of API key
// const { url } = require("inspector");
// const { request } = require("http");

const app=express();

app.set("view engine", "ejs"); // this tells the app generated by express to use ejs as its view engine - refer to the docs

// for encoding the data
app.use(bodyParser.urlencoded({extended:true})); // when the data is rendered from html file then the body parser requires this piece of code
app.use(express.static(__dirname + '/public')); // used for css files

app.get("/", function(req,res){
    res.sendFile(__dirname+"/index.html"); 
});

const apiKey= process.env.OPEN_WEATHER_API_KEY

app.post("/",function(req,res){
        request("https://api.openweathermap.org/data/2.5/weather?id=2172797&appid="+ apiKey +"", function(error, response, body){
            
            // to receive the api response in the JSON Format
            var dataAPI=JSON.parse(response.body);
            console.log(dataAPI);

        });
        const queryInput= req.body.cityName;
        const units= "metric";
        const url= "https://api.openweathermap.org/data/2.5/weather?q="+ queryInput +"&appid="+ apiKey +"&units="+ units +"";
        https.get(url, function(response){
            console.log(response.statusCode); // to get the status code in the terminal
            // while using the api call response data
            response.on("data", function(data){
                const weatherData= JSON.parse(data);
                const temp= weatherData.main.temp;
                const weatherDescription= weatherData.weather[0].description;
                const icon= weatherData.weather[0].icon;
                const imageUrl= "http://openweathermap.org/img/wn/" + icon + "@2x.png"; // to get the image related to the weather
                const maxTemp= weatherData.main.temp_max; // max current temperature of the city
                const lat= weatherData.coord.lat; // the latitude of the city
                const lon= weatherData.coord.lon; // the longitude of the city
                const hum= weatherData.main.humidity; // humidity percentage
                var visi= weatherData.visibility; // visibility in the air
                visi= visi/100;  // converting from meters to kilometers
                const clouds= weatherData.clouds.all;  // the percentage of cloudiness

                // const country=weatherData.sys.country;

                // for getting the northern/southern hemisphere
                var verticalHemisphere="";
                if(lat>=0)   verticalHemisphere="Northern";
                else    verticalHemisphere="Southern";

                // for getting the western/eastern hemisphere
                var horizontalHemisphere="";
                if(lon>=0)   horizontalHemisphere="Eastern";
                else    horizontalHemisphere="Western";

                // clody description
                var cloudyDesc="";
                if(clouds>=0 && clouds<=10) cloudyDesc="Sunny";
                else if(clouds>=11 && clouds<=19)   cloudyDesc="Fair";
                else if(clouds>=20 && clouds<=29)   cloudyDesc="Mostly sunny";
                else if(clouds>=30 && clouds<=59)   cloudyDesc="Partly cloudy";
                else if(clouds>=60 && clouds<=69)   cloudyDesc="Partly sunny";
                else if(clouds>=70 && clouds<=89)   cloudyDesc="Mostly Cloudy";
                else if(clouds>=90 && clouds<=100)  cloudyDesc="Overcast";

                //comfortability check based on humidity
                var comfort="";
                if(hum<=55) comfort="dry & comfortable";
                else if(hum>=56 && hum<=64) comfort="sticky with muggy evenings";
                else if(hum>=65) comfort="oppresive moisture";

                const query = queryInput.charAt(0).toUpperCase() + queryInput.slice(1); // capitalising the first letter of the entered query
                // const regionNamesInEnglish = new Intl.DisplayNames(['en'], { type: 'region' });  // coverting the two letter country abbreviation to full country name
                // const fullName= regionNamesInEnglish.of(country);  

                res.render('output',{city: query, temperature: temp, description: weatherDescription, image: imageUrl,
                                     maxTemperature: maxTemp, latitute: lat, longitude: lon, humidity: hum,
                                     visibility: visi, cloudiness: clouds, cloudDesc: cloudyDesc,
                                     vH: verticalHemisphere, hH: horizontalHemisphere, comfortLevel: comfort});   // sending additional info related to different fields

                res.end();
            });

        });
});

app.listen(5000 || process.env.PORT ,function(req,res){
    console.log("server is running at port 5000");
});

